# Generated by Django 5.1.1 on 2024-10-10 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucural', models.CharField(choices=[('PlazaOeste', 'Plaza Oeste'), ('MallAraucoMaipu', 'Mall Arauco Maipu'), ('CinepolisMaipu', 'Cinepolis Maipu'), ('PlazaOeste', 'Plaza Oeste'), ('PlazaVespucio', 'Plaza Vespucio')], max_length=100)),
                ('nombre', models.CharField(help_text='Nombre de la pelicula', max_length=50)),
                ('genero', models.CharField(choices=[('Accion', 'Accion'), ('Comedia', 'Comedia'), ('Drama', 'Drama'), ('Suspenso', 'Suspenso'), ('Crimen', 'Crimen'), ('Romance', 'Romance'), ('Terror', 'Terror'), ('Musical', 'Musical')], help_text='Genero de la pelicula', max_length=20)),
                ('clasificacion', models.CharField(choices=[('TE', 'TE'), ('TE+7', 'TE+7'), ('+14', '+14'), ('+18', '+18')], help_text='Clasificacion de la pelicula', max_length=8)),
                ('duracion', models.PositiveIntegerField(help_text='Tiempo de duración en minutos')),
                ('resena', models.TextField(blank=True, help_text='Breve reseña de la pelicula')),
                ('sala', models.IntegerField(help_text='Sala en la que se exhibe', validators=[django.core.validators.MinValueValidator(1, message='El número de sala debe ser mayor o igual a 1.'), django.core.validators.MaxValueValidator(15, message='El número de sala debe ser menor o igual a 15.')])),
                ('fecha_exhibicion', models.DateField(help_text='Fecha de exhibición')),
                ('hora_exhibicion', models.TimeField(help_text='Hora de exhibición')),
                ('valor_ticket', models.PositiveIntegerField(help_text='Valor del ticket')),
                ('imagen', models.ImageField(upload_to='peliculas/')),
            ],
        ),
    ]
