# Generated by Django 5.1.1 on 2024-10-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloPeliculas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='sucural',
            new_name='sucursal',
        ),
    ]
